DROP TABLE BOARD;
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;
CREATE TABLE BOARD(
	BID NUMBER(4) PRIMARY KEY,
	CID VARCHAR2(20) REFERENCES CUSTOMER(CID),
	BTITLE VARCHAR2(300) NOT NULL,
	BCONTENT VARCHAR2(500) NOT NULL,
	BHIT NUMBER(4) DEFAULT 0,
	BGROUP NUMBER(4) NOT NULL,
	BSTEP NUMBER(4) NOT NULL,
	BINDENT NUMBER(4) NOT NULL,
	BIP VARCHAR(20) NOT NULL,
	BRDATE DATE DEFAULT SYSDATE );
--답변글쓰기
INSERT INTO BOARD (BID, CID, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP) VALUES
			(BOARD_SEQ.NEXTVAL, 'topwings', '답변', '내용', 1, 1, 1, '192.168.24.7');
--------DAO-----------
--글갯수
SELECT COUNT(*) FROM BOARD;
--글목록 가져오기
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT B.* FROM BOARD B, CUSTOMER C WHERE B.CID=C.CID ORDER BY BGROUP DESC, BSTEP) A ) WHERE RN BETWEEN 1 AND 11;
--원글쓰기
INSERT INTO BOARD (BID, CID, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP) VALUES
			(BOARD_SEQ.NEXTVAL, 'topwings', '제목', '내용', BOARD_SEQ.CURRVAL, 0, 0, '192.168.24.7');
--조회수올리기
UPDATE BOARD SET BHIT = BHIT+1 WHERE BID=1;
--글 수정과 상세보기, 글번호로 DTO가져오기
SELECT B.* FROM BOARD B, CUSTOMER C WHERE B.CID=C.CID AND BID=3;
--글 수정하기
UPDATE BOARD SET BTITLE='수정제목', BCONTENT='수정내용', BRDATE=SYSDATE WHERE BID=1;
--글 삭제하기
DELETE FROM BOARD WHERE BID=2;
--STEP A
UPDATE BOARD SET BSTEP = BSTEP+1 WHERE BGROUP=1 AND BSTEP>0;
--답변글 쓰기
INSERT INTO BOARD (BID, CID, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP) VALUES
			(BOARD_SEQ.NEXTVAL, 'topwings', '답변글제목', '답변글내용', 1, 1, 1, '192.168.20.44');
SELECT * FROM BOARD;
COMMIT;
