DROP TABLE CUSTOMER ;
CREATE TABLE CUSTOMER(
 CID VARCHAR2(20) PRIMARY KEY,
 CPASS VARCHAR2(20) NOT NULL,
 CNAME VARCHAR2(20) NOT NULL,
 CTEL  VARCHAR2(20) NOT NULL,
 CADDRESS VARCHAR2(20) NOT NULL,
 CRDATE DATE DEFAULT SYSDATE,
 CRESULT NUMBER(1) DEFAULT 0 );
SELECT * FROM CUSTOMER;
--ID 중복체크
SELECT * FROM CUSTOMER WHERE CID='aaa';
--회원 가입
INSERT INTO CUSTOMER (CID, CPASS, CNAME, CTEL, CADDRESS ) VALUES ('topwings','xhddlf','임상훈','010-7118-7173','서울강북');
--회원 로그인 (CID, CPASS)
SELECT * FROM CUSTOMER WHERE CID='cID' AND CPASS='cPASS';
--회원 정보수정 (ID로 DTO가져오기)
SELECT * FROM CUSTOMER WHERE CID='cID';
--정보수정
UPDATE CUSTOMER SET CPASS='', CNAME='',CTEL='',CADDRESS='' WHERE CID=''; 
--회원 탈퇴
DELETE FROM CUSTOMER WHERE CID='CID';
--회원 당첨
UPDATE CUSTOMER SET CRESULT=1 WHERE CID='topwings';
COMMIT;
