DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
 PCODE VARCHAR2(50) PRIMARY KEY,
 PBRAND VARCHAR2(50) NOT NULL,
 PNAME VARCHAR2(50) NOT NULL,
 PIMG1 VARCHAR2(50) DEFAULT 'NOIMG1.PNG' NOT NULL,
 PIMG2 VARCHAR2(50) DEFAULT 'NOIMG2.PNG' NOT NULL,
 PIMG3 VARCHAR2(50) DEFAULT 'NOIMG3.PNG' NOT NULL,
 PIMG4 VARCHAR2(50) DEFAULT 'NOIMG4.PNG' NOT NULL,
 PINFO VARCHAR2(500)
);
--상품등록
 INSERT INTO PRODUCT (PCODE, PBRAND, PNAME, PIMG1, PIMG2, PIMG3, PIMG4, PINFO) VALUES
 		('Y-002', 'YAMAHA', 'Y-PIANO01', 'Y1.PNG', 'Y2.PNG', 'Y3.PNG', 'Y4.PNG', '왜또안되드나');
--상품 전체 검색
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM PRODUCT ORDER BY PCODE DESC) A ) WHERE RN BETWEEN 1 AND 6;
--브랜드별 검색 
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM PRODUCT WHERE PBRAND='YAMAHA' ORDER BY PCODE) A ) WHERE RN BETWEEN 1 AND 3;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM PRODUCT WHERE PBRAND like '%'||''||'%' ORDER BY PCODE) A ) WHERE RN BETWEEN 1 AND 10;
--TOTCNT
SELECT COUNT(*) FROM PRODUCT WHERE PBRAND LIKE '%'||'YAMAHA'||'%';
--상품 상세보기  (pcode로 dto가져오기
SELECT * FROM PRODUCT WHERE PCODE='';
--상품 수정
 UPDATE PRODUCT SET PIMG1='CY1', PIMG2='CY2', PIMG3='CY3', PIMG4='CY4', PINFO='바꾼내용' WHERE PCODE='Y-001';
--상품 삭제
DELETE FROM PRODUCT WHERE PCODE='Y-001';
SELECT * FROM PRODUCT;
 UPDATE PRODUCT SET PBRAND='KAWAI', PNAMD='SK-3' WHERE PC
COMMIT;
